=== mstitop/SmartETL/smartETL/src/main/resources/job.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by dennis (Fannie Mae/PO#HQR-3000034226) -->
<!-- edited with XMLSpy v2015 sp2 (http://www.altova.com) by Dennis (Webfly) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1" jxb:version="1.0">
	<xs:element name="job">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
			<xs:appinfo>
				<jxb:class name="XMLJob"/>
			</xs:appinfo>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="properties" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="property">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string"/>
									<xs:attribute name="value" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="steps">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="step">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="flows">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="flow">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="from" type="xs:string"/>
										<xs:element name="to" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="datadefs" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="datadef" type="datadef"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="lookups" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="datadef">
		<xs:annotation>
			<xs:appinfo>
				<jxb:class name="XMLDataDef"/>
			</xs:appinfo>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="fields">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="field">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="name" type="xs:string"/>
									<xs:element name="type" type="xs:string"/>
									<xs:element name="length" type="xs:int"/>
									<xs:element name="format" type="xs:string" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="excludes" minOccurs="0">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="field" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="parent" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="lookup">
		<xs:annotation>
			<xs:appinfo>
				<jxb:class name="XMLLookup"/>
			</xs:appinfo>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="datadef" type="datadef"/>
			<xs:element name="inmemory" type="xs:boolean"/>
			<xs:element name="sourcetype" type="xs:string"/>
			<xs:element name="database" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="type"/>
						<xs:element name="url"/>
						<xs:element name="user"/>
						<xs:element name="password"/>
						<xs:element name="sql"/>
						<xs:element name="loadall"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="file" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="path"/>
						<xs:element name="delimiter"/>
						<xs:element name="quote"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="keys">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="field"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="values">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="field"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StepDef">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="type" type="xs:string"/>
			<xs:element name="debug" type="xs:boolean"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SmartTransStepDef">
		<xs:complexContent>
			<xs:extension base="StepDef">
				<xs:sequence>
					<xs:element name="tag" minOccurs="0">
						<xs:complexType>
							<xs:attribute name="value" type="xs:string" use="optional"/>
							<xs:attribute name="formula" type="xs:string" use="optional"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="datadef" type="datadef"/>
					<xs:element name="variables" minOccurs="0">
						<xs:complexType>
							<xs:sequence maxOccurs="unbounded">
								<xs:element name="variable">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="name" type="xs:string"/>
											<xs:element name="formula" type="xs:string"/>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="mappings">
						<xs:complexType>
							<xs:sequence maxOccurs="unbounded">
								<xs:element name="mapping">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="field" type="xs:string"/>
											<xs:sequence maxOccurs="unbounded">
												<xs:element name="formula">
													<xs:complexType>
														<xs:attribute name="tag" type="xs:string"/>
														<xs:attribute name="ref" type="xs:string" use="optional"/>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="filter" minOccurs="0">
						<xs:complexType>
							<xs:sequence maxOccurs="unbounded">
								<xs:element name="formula">
									<xs:complexType>
										<xs:attribute name="tag" type="xs:string"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="externalprocess">
						<xs:complexType>
							<xs:attribute name="class" type="xs:string"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="validator"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="JoinStepDef">
		<xs:complexContent>
			<xs:extension base="StepDef">
				<xs:sequence>
					<xs:element name="jointype"/>
					<xs:element name="leftstep">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="name"/>
								<xs:element name="keys">
									<xs:complexType>
										<xs:sequence maxOccurs="unbounded">
											<xs:element name="field"/>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="rightstep">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="name"/>
								<xs:element name="keys">
									<xs:complexType>
										<xs:sequence maxOccurs="unbounded">
											<xs:element name="field"/>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SortStepDef">
		<xs:complexContent>
			<xs:extension base="StepDef">
				<xs:sequence>
					<xs:element name="tempdirectory" type="xs:string"/>
					<xs:element name="prefix" type="xs:string"/>
					<xs:element name="sortsize" type="xs:int"/>
					<xs:element name="freememory" type="xs:int"/>
					<xs:element name="compress" type="xs:boolean"/>
					<xs:element name="uniquerows" type="xs:boolean"/>
					<xs:element name="fields">
						<xs:complexType>
							<xs:sequence maxOccurs="unbounded">
								<xs:element name="field">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="name" type="xs:string"/>
											<xs:element name="ascending" type="xs:boolean"/>
											<xs:element name="casesensitive" type="xs:boolean"/>
											<xs:element name="presorted" type="xs:boolean"/>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== mstitop/SmartETL/examples/samplejobtemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 sp2 (http://www.altova.com) by Dennis (Webfly) -->
<job xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Work/workspace/incredible/smartETL/src/main/resources/job.xsd">
	<name/>
	<properties></properties>
	<steps>
		<step>
			<name>step1-CSVInput</name>
			<type>CSVInputStep</type>
			<variables>
				<variable>
					<name>v1</name>
					<formula>[firstname]</formula>
				</variable>
			</variables>
			<!-- filter>left([v1];1)="j"</filter-->
			<filter>nullempty([v1])&lt;&gt;""</filter>
			<file>C:\Work\workspace\incredible\examples\customers1.txt</file>
			<title>true</title>
			<delimiter>;</delimiter>
			<quote/>
			<datadef ref="customer"/>
			<!--topskipcount>2</topskipcount-->
			<bottomskipcount>10</bottomskipcount>
		</step>
		<step>
			<name>step6-CSVInput</name>
			<type>CSVInputStep</type>
			<file>C:\Work\workspace\incredible\examples\state.txt</file>
			<title>true</title>
			<delimiter>;</delimiter>
			<quote/>
			<datadef ref="state"/>
		</step>
		<step>
			<name>step5-Join</name>
			<type>JoinStep</type>
			<jointype>LEFT OUTER</jointype>
			<leftstep>
				<name>step7-sort</name>
				<keys>
					<field>zip</field>
					<field>stateCode</field>
				</keys>
			</leftstep>
			<rightstep>
				<name>step71-sort</name>
				<keys>
					<field>zip</field>
					<field>stateCode</field>
				</keys>
			</rightstep>
		</step>
		<step>
			<name>step2-Dummy</name>
			<type>DummyStep</type>
			<debug>true</debug>
		</step>
		<step>
			<name>step3-CSVOutputSep</name>
			<type>CSVOutputStep</type>
			<file>C:\Work\workspace\smartETLTest\output\outputcustomers.txt</file>
			<title>true</title>
			<delimiter>;</delimiter>
			<quote/>
			<!-- datadef ref="outputcustomer"/-->
		</step>
		<step>
			<name>step1Output</name>
			<type>CSVOutputStep</type>
			<file>C:\Work\workspace\smartETLTest\output\customers_cmbi.txt</file>
			<title>true</title>
			<delimiter>;</delimiter>
			<quote/>
			<!-- datadef ref="outputcustomer"/-->
		</step>
		<step>
			<name>step 4-smart trans step</name>
			<type>SmartTransStep</type>
			<datadef ref="outputcustomer"/>
			<!--tag value="HK" formula="HK1"/-->
			<tag formula="&quot;HK&quot;"/>
			<variables>
				<variable>
					<name>v1</name>
					<formula>[firstname]</formula>
				</variable>
				<variable>
					<name>v2</name>
					<formula>"A"</formula>
				</variable>
			</variables>
##mappings##
		</step>
		<step>
			<name>step7-sort</name>
			<type>SortStep</type>
			<tempdirectory>C:\Work\workspace\smartETLTest\temp</tempdirectory>
			<prefix>sort_</prefix>
			<sortsize>200</sortsize>
			<compress>true</compress>
			<uniquerows>false</uniquerows>
			<fields>
				<field>
					<name>zip</name>
					<ascending>true</ascending>
					<casesensitive>true</casesensitive>
					<presorted>false</presorted>
				</field>
				<field>
					<name>stateCode</name>
					<ascending>true</ascending>
					<casesensitive>true</casesensitive>
					<presorted>false</presorted>
				</field>
			</fields>
		</step>
		<step>
			<name>step71-sort</name>
			<type>SortStep</type>
			<tempdirectory>C:\Work\workspace\smartETLTest\temp</tempdirectory>
			<prefix>sort_</prefix>
			<sortsize>200</sortsize>
			<compress>true</compress>
			<uniquerows>false</uniquerows>
			<fields>
				<field>
					<name>zip</name>
					<ascending>true</ascending>
					<casesensitive>true</casesensitive>
					<presorted>false</presorted>
				</field>
				<field>
					<name>stateCode</name>
					<ascending>true</ascending>
					<casesensitive>true</casesensitive>
					<presorted>false</presorted>
				</field>
			</fields>
		</step>
		<step>
			<name>step8-sort</name>
			<type>SortStep</type>
			<tempdirectory>C:\Work\workspace\smartETLTest\temp</tempdirectory>
			<prefix>sort_</prefix>
			<sortsize>200</sortsize>
			<compress>true</compress>
			<uniquerows>false</uniquerows>
			<fields>
				<field>
					<name>id</name>
					<ascending>true</ascending>
					<casesensitive>true</casesensitive>
					<presorted>false</presorted>
				</field>
			</fields>
		</step>
	</steps>
	<flows>
		<!-- flow>
		<from>step1-CSVInput</from>
		<to>step 4-smart trans step</to>
	</flow>
	<flow>
		<from>step 4-smart trans step</from>
		<to>step3-CSVOutputSep</to>
	</flow-->
		<flow>
			<from>step1-CSVInput</from>
			<to>step7-sort</to>
		</flow>
		<flow>
			<from>step6-CSVInput</from>
			<to>step71-sort</to>
		</flow>
		<flow>
			<from>step7-sort</from>
			<to>step5-Join</to>
		</flow>
		<flow>
			<from>step71-sort</from>
			<to>step5-Join</to>
		</flow>
		<flow>
			<from>step5-Join</from>
			<to>step 4-smart trans step</to>
		</flow>
		<flow>
			<from>step 4-smart trans step</from>
			<to>step8-sort</to>
		</flow>
		<flow>
			<from>step8-sort</from>
			<to>step3-CSVOutputSep</to>
		</flow>
		<flow>
			<from>step1-CSVInput</from>
			<to>step1Output</to>
		</flow>
	</flows>
	<!--flow>
		<from>step1-CSVInput</from>
		<to>step5-Join</to>
	</flow>
	<flow>
		<from>step6-CSVInput</from>
		<to>step5-Join</to>
	</flow>
	<flow>
		<from>step5-Join</from>
		<to>step3-CSVOutputSep</to>
	</flow-->
	<!--flow>
		<from>step1-CSVInput</from>
		<to>step 5-smart trans step</to>
	</flow>
	<flow>
		<from>step 4-smart trans step</from>
		<to>step3-CSVOutputSep</to>
	</flow-->
	<datadefs>
		<datadef>
			<name>customer</name>
			<fields>
				<field>
					<name>id</name>
					<type>Integer</type>
					<length>3</length>
				</field>
				<field>
					<name>name</name>
					<type>String</type>
					<length>10</length>
				</field>
				<field>
					<name>firstname</name>
					<type>String</type>
					<length>13</length>
				</field>
				<field>
					<name>zip</name>
					<type>Integer</type>
					<length>5</length>
				</field>
				<field>
					<name>city</name>
					<type>String</type>
					<length>8</length>
				</field>
				<field>
					<name>birthdate</name>
					<type>Date</type>
					<length>10</length>
					<format>yyyy/mm/dd</format>
				</field>
				<field>
					<name>street</name>
					<type>String</type>
					<length>11</length>
				</field>
				<field>
					<name>housenr</name>
					<type>Integer</type>
					<length>3</length>
				</field>
				<field>
					<name>stateCode</name>
					<type>String</type>
					<length>9</length>
				</field>
				<field>
					<name>state</name>
					<type>String</type>
					<length>30</length>
				</field>
			</fields>
		</datadef>
		<datadef>
			<name>state</name>
			<fields>
				<field>
					<name>zip</name>
					<type>Integer</type>
					<length>5</length>
				</field>
				<field>
					<name>stateCode</name>
					<type>String</type>
					<length>9</length>
				</field>
				<field>
					<name>population</name>
					<type>Integer</type>
					<length>8</length>
				</field>
			</fields>
		</datadef>
		<datadef parent="customer">
			<name>outputcustomer</name>
			<fields>
				<field>
					<name>newfld</name>
					<type>String</type>
					<length>9</length>
				</field>
				<field>
					<name>lkfld</name>
					<type>Integer</type>
					<length>9</length>
				</field>
				<field>
					<name>population</name>
					<type>Integer</type>
					<length>9</length>
				</field>
			</fields>
			<excludes>
				<field>stateCode</field>
			</excludes>
		</datadef>
	</datadefs>
	<lookups>
		<lookup>
			<name>testlookup</name>
			<datadef ref="customer"/>
			<sourcetype>file</sourcetype>
			<file>
				<path>C:\Work\workspace\incredible\examples\customers1.txt</path>
				<delimiter>;</delimiter>
				<quote/>
			</file>
			<keys>
				<field>id</field>
				<field>name</field>
			</keys>
			<values>
				<field>firstname</field>
				<field>city</field>
			</values>
		</lookup>
	</lookups>
</job>
